trigger:
- none

pool:
  vmImage: 'windows-latest'

stages:
  - stage: Dev
    displayName: Dev
    jobs:
      - deployment: Deploy
        displayName: Deploy Basic Terraform Infrastructure
        environment: Dev
        variables:
          - group: ARM
          - group: Basic
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self             
                - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
                  displayName: Install Terraform
                  inputs:
                    terraformVersion: '1.0.9'
                - task: TerraformTaskV2@2
                  displayName: Terraform Init
                  inputs:
                    provider: 'azurerm'
                    command: 'init'
                    workingDirectory: 'Platform/Terraform-Basic'
                    backendServiceArm: 'sp-devops-pipeline'
                    backendAzureRmResourceGroupName: '$(ARM.ResourceGroup.Name)'
                    backendAzureRmStorageAccountName: '$(ARM.StorageAccount.Name)'
                    backendAzureRmContainerName: '$(ARM.StorageAccount.Container.Name)'
                    backendAzureRmKey: 'basic.tfstate'
                - task: TerraformTaskV2@2
                  displayName: Terraform Plan
                  inputs:
                    provider: 'azurerm'
                    command: 'plan'
                    workingDirectory: 'Platform/Terraform-Basic'
                    environmentServiceNameAzureRM: 'sp-devops-pipeline'
                - task: TerraformTaskV2@2
                  displayName: Terraform Apply
                  inputs:
                    provider: 'azurerm'
                    command: 'apply'
                    workingDirectory: 'Platform/Terraform-Basic'
                    environmentServiceNameAzureRM: 'sp-devops-pipeline'
                # - task: TerraformTaskV2@2
                #   displayName: Terraform Destroy
                #   inputs:
                #     provider: 'azurerm'
                #     command: 'destroy'
                #     workingDirectory: 'Platform/Terraform-Basic'
                #     environmentServiceNameAzureRM: 'sp-devops-pipeline'